site_name: Conexión Saludable 2026
site_description: Documentación estratégica y operativa (Granvita)
site_url: https://miguel-toracom.github.io/conexion-saludable-granvita
repo_url: https://github.com/miguel-toracom/conexion-saludable-granvita

# Tu contenido está dentro de esta carpeta:
docs_dir: CONEXION_SALUDABLE_PROPOSAL

theme:
  name: material
  logo: img/toracom-horizontal-blanco.png
  favicon: img/favicon.png
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.action.edit
    - content.code.copy
    - content.tooltips
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple

nav:
  - Inicio: "index.md"
  - "Nort Start":
    - "0.1 One-Slide - North Star de Conexión Saludable": "Nort Start/0.1 One‑Slide - North Star de Conexión Saludable"

  - "Estrategia":
    - "Storydeck Comité Granvita 2026": "1 Estrategia/1.0 Storydeck Comité Granvita 2026.md"
    - "Estrategia Maestra – Conexión Saludable 2026": "1 Estrategia/1.1 Estrategia Maestra – Conexión Saludable 2026.md"
    - "North Star & KPI Tree – Conexión Saludable 2026": "1 Estrategia/1.2 North Star & KPI Tree – Conexión Saludable 2026.md"
    - "Roadmap 30-60-90 y Plan Anual": "1 Estrategia/1.3 Roadmap 30-60-90 y Plan Anual.md"

  - "Programa y Arquitectura":
    - "Blueprint de Automatización, CRM y CDP": "2 Programa y Arquitectura/2.0 Blueprint de Automation, CRM y CDP.md"
    - "Modelo de Scoring – Lead & Engagement": "2 Programa y Arquitectura/2.1 Modelo de Scoring – Lead & Engagement.md"
    - "Diccionario de Datos y Eventos de Tracking": "2 Programa y Arquitectura/2.2 Diccionario de Datos y Eventos de Tracking.md"
    - "Journeys y Nurtures": "2 Programa y Arquitectura/2.3 Journeys y Nurtures.md"
    - "RACI, Gobernanza y Rituales": "2 Programa y Arquitectura/2.4 RACI, Gobernanza y Rituales.md"

  - "Contenido y Canales":
    - "Playbook - Derivación de Webinar a Podcast, Clips y Landing": "3 Contenido y Canales/3.0 Playbook - Derivación de Webinar a Podcast, Clips y Landing.md"
    - "Patrones de Landing Pages y Wireframes": "3 Contenido y Canales/3.1 Patrones de Landing Pages y Wireframes.md"
    - "Calendario Editorial Quincenal – Conexión Saludable 2026": "3 Contenido y Canales/3.2 Calendario Editorial Quincenal – Conexión Saludable 2026.md"
    - "Guía de Redistribución por WhatsApp y Programa de Referidos": "3 Contenido y Canales/3.3 Guía de Redistribución por WhatsApp y Programa de Referidos.md"

  - "Medición y Aprendizaje":
    - "Plan de Medición y Atribución": "4 Medición y Aprendizaje/4.0 Plan de Medición y Atribución.md"
    - "Tabla de Métricas, Definiciones y Objetivos": "4 Medición y Aprendizaje/4.1 Tabla de Métricas, Definiciones y Objetivos.md"
    - "Dashboard Specs – GA4, CRM, Email y WhatsApp": "4 Medición y Aprendizaje/4.2 Dashboard Specs – GA4, CRM, Email y WhatsApp.md"
    - "Plan de Experimentación A-B y Ritmo de Sprints": "4 Medición y Aprendizaje/4.3 Plan de Experimentación A-B y Ritmo de Sprints.md"

  - "Riesgos y Cumplimiento":
    - "Riesgos y Mitigaciones – Conexión Saludable 2026": "5 Riesgos y Cumplimiento/5.0 Riesgos y Mitigaciones – Conexión Saludable 2026.md"
    - "Política de Privacidad, Consentimiento y Gestión de PII": "5 Riesgos y Cumplimiento/5.1 Política de Privacidad, Consentimiento y Gestión de PII.md"

  - "Alianzas y Comunidad":
    - "Tesis de Alianzas con Academias, Colegios y Laboratorios": "6 Alianzas y Comunidad/6.0 Tesis de Alianzas con Academias, Colegios y Laboratorios.md"
    - "Programa de Lealtad – Concepto, Mecánicas y Reglas": "6 Alianzas y Comunidad/6.1 Programa de Lealtad – Concepto, Mecánicas y Reglas.md"

  - "Anexos":
    - "FAQ de Dirección y Mensajes Clave": "99_Anexos/9.0 FAQ de Dirección y Mensajes Clave.md"
    - "Plantillas de Copia – Email, WhatsApp y Landing Page": "99_Anexos/9.1 Plantillas de Copia – Email, WhatsApp y Landing Page.md"

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed
  - toc:
      permalink: true

# Soporte Mermaid
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

extra_css:
  - styles/extra.css

plugins:
  - search
  - mermaid2